# Generated by Django 4.2 on 2023-04-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.base')),
            ],
        ),
    ]
