# Generated by Django 4.2 on 2023-04-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
